### PR TITLE
doc: Add and modify Offline First code of conduct

### PR DESCRIPTION
**Pull request by gee-forr**
OK - here's a first draft. I dunno if you wanna put something in there specifically about recruiters, or if you feel the general harassment points should be sufficient.

My 2c. It's sufficient, as there's a clause around the code of conduct being extended with specific rules for certain channel.s

### CODE REVIEW

**Comment by martincronje** [comment]
Looks cool. Very comprehensive.

Should we tell people where they can get a list of admins to contact if they need to?

It may be worthwhile to mention advertising, recruitment as a separate line-item?

**Comment by gee-forr** [comment]
@martincronje There is a link that tells them where to get the list. Also, what are your suggestions around recruitment?

**Comment by kennethkalmer** [comment]
This definitely gets my :+1:

Thanks @gee-forr for the awesome work! I'll let the channels know, how long should we give for feedback?

**Comment by constantm** [comment]
Damn. No more virtual hugs without consent.

**Comment by garrensmith** [comment]
This is looking great. We need something about recruitment.

**Comment by emilesilvis** [comment]
:+1: 

What are the current thoughts around recruitment and advertising?

**Comment by kennethkalmer** [comment]
My 2c on the recruitment story is:
1. Professional recruiters are not welcome, at all
2. Users don't share the details of others with recruiters without their explicit consent
3. Advertising an opportunity in brief is acceptable, discussions happen behind the scenes from there
4. Opportunities should not be blatant referral program links where to poster hopes to earn a commission, this is recruiting.

We should still be able to attract good talent to our teams, and brief messages should allow it. Same goes for new teams, founders should be able to say "We're hiring".

It is a fine line, but definitely (1) & (2) is the most important to me.

**Comment by gee-forr** [comment]
OK - I'll rev the wordsmithing engine up. Stand by for a new commit.

**Comment by kennethkalmer** [comment]
#4 is still outstanding, but I don't see that as blocker. Can we get this merged in the meantime?

This is a living document, and I don't want us stuck in this awkward place ;) We need to be in the channels sharing and growing the community.

**Comment by kennethkalmer** [comment]
Big thanks to @gee-forr & @SPARTAN563 for pouring so much time and effort into this!

**Comment by gee-forr** [comment]
@kennethkalmer no probs. :) Once you're happy with this, merge it back to #2 and I'll add a TL;DR. After that, I think we should publish.

**Comment by kennethkalmer** [comment]
@gee-forr I added the TL;DR already, have a look :)

**Comment by gee-forr** [comment]
NICE! May I have the honour of merging?

**Pull request merged**
